---
# tasks file for nginx
- name: Installing the latest nginx for redhat/centos
  yum:
    name: nginx
    state: latest
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'Red Hat Enterprise Linux'

- name: Installing the latest nginx for debian/ubuntu
  apt:
    name: nginx
    state: latest
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Ensuring nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes

