---
- name: Getting basic system info
  debug:
    msg: 
      - "fqdn: {{ ansible_facts['fqdn'] }}"
      - "hostname: {{ ansible_facts['hostname'] }}"
      - "default ipv4: {{ ansible_facts['default_ipv4']['address'] }}"
      - "cpus: {{ ansible_facts['processor_count'] }}"
      - "memory: {{ ansible_facts['memtotal_mb'] }}"
      - "distro: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
