---
- name: Ensuring latest packeges...
  yum:
    name:
      - "{{ firewall_pkg }}"
      - "{{ web_pkg }}"
      - "{{ ssl_pkg }}"

- name: Ensuring httpd.conf present...
  copy:
    src: "{{ httpdconf_src }}"
    dest: "{{ httpdconf_desst }}"
    owner: root
    group: root
    mode: 0644
  notify: restarting httpd

- name: Ensuring secrets dir present...
  file:
    state: directory
    recurse: true
    path: "{{ secrets_dir }}"
    owner: apache
    group: apache
    mode: 0500

- name: Ensuring htpasswd present
  copy:
    src: "{{ secrets_src }}"
    dest: "{{ secrets_dest }}"
    owner: apache
    group: apache
    mode: 0400

- name: Ensuring .htaccess present...
  copy:
    src: "{{ htaccess_src }}"
    dest: "{{ web_root }}/.htaccess"
    owner: apache
    group: apache
    mode: 0400

- name: Generating index.html...
  copy:
    content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4']['address'] }}) has been customized by Ansible."
    dest: "{{ web_root }}/index.html"

- name: Ensuring firewalld and httpd enabled/started...
  service:
    name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - "{{ firewall_svc }}"
      - "{{ web_svc }}"

- name: Ensuring firewall rules added...
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https

